# Generated by Django 3.2.3 on 2021-06-07 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('logo', models.ImageField(default='https://place-hold.it/100x60', upload_to='company_images')),
                ('description', models.TextField(max_length=2056)),
                ('employee_count', models.PositiveIntegerField()),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('picture', models.ImageField(default='https://place-hold.it/100x60', upload_to='speciality_images')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('skills', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=2056)),
                ('salary_min', models.PositiveIntegerField()),
                ('salary_max', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='step_job.company')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='step_job.specialty')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('Не ищу работу', 'Not In Search'), ('Рассматриваю предложения', 'Consideration'), ('Ищу работу', 'In Search')], max_length=64)),
                ('salary', models.PositiveIntegerField()),
                ('specialty', models.CharField(choices=[('Фронтенд', 'Frontend'), ('Бэкенд', 'Backend'), ('Геймдев', 'Gamedev'), ('Девопс', 'Devops'), ('Дизайн', 'Design'), ('Продукты', 'Products'), ('Менеджмент', 'Management'), ('Тестирование', 'Testing')], max_length=512)),
                ('grade', models.CharField(choices=[('intern', 'Intern'), ('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead')], max_length=64)),
                ('education', models.CharField(choices=[('Отсутствует', 'Missing'), ('Среднее', 'Secondary'), ('Средне-специальное', 'Vocational'), ('Неполное высшее', 'Incomplete Higher'), ('Высшее', 'Higher')], max_length=64)),
                ('experience', models.CharField(max_length=512)),
                ('portfolio', models.TextField(max_length=1028)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(max_length=64)),
                ('written_phone', models.CharField(max_length=12)),
                ('written_cover_letter', models.TextField(max_length=2058)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='step_job.vacancy')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
            },
        ),
    ]
